runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 16
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7
  target_concurrent_requests: 100