const DEFAULT_POLICY = {
	basic_rate: {
		title: "Basic rate",
		description: "The basic rate is the first of three tax brackets on all income, after allowances are deducted.",
		default: 20,
		value: 20,
		summary: "Change the basic rate to @%",
		type: "rate",
	},
	higher_rate: {
		title: "Higher rate",
		description: "The higher rate is the middle tax bracket.",
		default: 40,
		value: 40,
		summary: "Change the higher rate to @%",
		type: "rate",
	},
	add_rate: {
		title: "Additional rate",
		description: "The additional rate is the highest tax bracket, with no upper bound.",
		default: 45,
		value: 45,
		summary: "Change the additional rate to @%",
		type: "rate",
	},
	basic_threshold: {
		title: "Basic rate threshold",
		description: "Lower threshold for the basic rate, on income after allowances (including the personal allowance) have been deducted.",
		default: 0,
		value: 0,
		max: 100000,
		summary: "Change the basic rate to £@/year",
		type: "yearly",
	},
	higher_threshold: {
		title: "Higher rate threshold",
		description: "The lower threshold for the higher rate of income tax (and therefore the upper threshold of the basic rate).",
		default: 37500,
		value: 37500,
		max: 200000,
		summary: "Change the higher rate to £@/year",
		type: "yearly",
	},
	add_threshold: {
		title: "Additional rate",
		description: "The lower threshold for the additional rate.",
		default: 150000,
		value: 150000,
		max: 1000000,
		summary: "Change the additional rate to £@/year",
		type: "yearly",
	},
	personal_allowance: {
		title: "Personal allowance",
		description: "The personal allowance is deducted from general income.",
		default: 12500,
		value: 12500,
		max: 25000,
		summary: "Change the personal allowance to £@/year",
		type: "yearly",
	},
	NI_main_rate: {
		title: "NI main rate",
		description: "The Class 1 NI main rate is paid on employment earnings between the Primary Threshold and the Upper Earnings Limit.",
		default: 12,
		value: 12,
		summary: "Change the NI main rate to @%",
		type: "rate",
	},
	NI_add_rate: {
		title: "NI additional rate",
		description: "The Class 1 NI additional rate is paid on employment earnings above the Upper Earnings Limit.",
		default: 2,
		value: 2,
		summary: "Change the NI additional rate to @%",
		type: "rate",
	},
	NI_PT: {
		title: "NI Primary Threshold",
		description: "The Primary Threshold is the lower bound for the main rate of NI.",
		default: 183,
		value: 183,
		max: 1000,
		summary: "Change the PT to £@/week",
		type: "weekly",
	},
	NI_UEL: {
		title: "NI Upper Earnings Limit",
		description: "The Upper Earnings Limit is the upper bound for the main rate of NI.",
		default: 962,
		value: 962,
		max: 10000,
		summary: "Change the UEL to £@/week",
		type: "weekly",
	},
	child_UBI: {
		title: "Child UBI",
		description: "A basic income for children is given to every child aged under 18, regardless of household income.",
		default: 0,
		value: 0,
		max: 250,
		summary: "Give a basic income of £@/week to children",
		type: "weekly",
	},
	adult_UBI: {
		title: "Adult UBI",
		description: "Basic income for adults is given to individuals aged over 18 but under State Pension age.",
		default: 0,
		value: 0,
		max: 250,
		summary: "Give a basic income of £@/week to adults",
		type: "weekly",
	},
	senior_UBI: {
		title: "Senior UBI",
		description: "A basic income for senior citizens is given to those over State Pension age.",
		default: 0,
		value: 0,
		max: 250,
		summary: "Give a basic income of £@/week to seniors",
		type: "weekly",
	},
	abolish_savings_allowance: {
		title: "Personal Savings Allowance",
		description: "The Personal Savings Allowance is the amount of taxable savings interest income disregarded for Income Tax purposes. It has different values at different Income Tax bands - this switch abolishes all of them.",
		default: false,
		value: false,
		summary: "Abolish the Personal Savings Allowance",
		type: "bool"
	},
	abolish_dividend_allowance: {
		title: "Dividend Allowance",
		description: "The Dividend Allowance disregards up to £2,000 of taxable dividend income per year. This switch abolishes it.",
		default: false,
		value: false,
		summary: "Abolish the Dividend Allowance",
		type: "bool"
	},
	abolish_income_tax: {
		title: "Income Tax",
		description: "Income Tax raises over £190bn per year. This switch abolishes it.",
		default: false,
		value: false,
		summary: "Abolish Income Tax",
		type: "bool"
	},
	abolish_NI: {
		title: "National Insurance",
		description: "This switch abolishes National Insurance.",
		default: false,
		value: false,
		summary: "Abolish National Insurance",
		type: "bool"
	},
	abolish_UC: {
		title: "Abolish Universal Credit",
		description: "Universal Credit is the main means-tested benefit, currently being rolled out across the country.",
		default: false,
		value: false,
		summary: "Abolish Universal Credit",
		type: "bool"
	},
	abolish_CB: {
		title: "Abolish Child Benefit",
		description: "Child Benefit is a universal allowance to parents of children, with a means test embedded in Income Tax.",
		default: false,
		value: false,
		summary: "Abolish Child Benefit",
		type: "bool"
	},
};

export default DEFAULT_POLICY;
